name: docker

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - run: |
          TAG=${{ github.sha }}
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && TAG=$(echo $VERSION | sed -e 's/^v//')
          IMAGE_NAME=$(echo ${{ github.repository }} | sed -e 's/.*\///')
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME:$TAG
          docker build . --file Dockerfile --tag $IMAGE_ID
          docker push $IMAGE_ID
